version: 2

sources:
  - name: dbt_acastagna
    database: analytics
    schema: dbt_acastagna
    tables:
      - name: ciao
    freshness: 
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
